version: 2
updates:
  - package-ecosystem: "maven"
    target-branch: "main"
    directory: "/"
    schedule:
      interval: "daily"
      time: "00:00"
    ignore:
      - dependency-name: "org.apache.iotdb:iotdb-session"
        update-types: ["version-update"]
        version: ["> 1.3.4"]
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "daily"
      time: "00:00x"